

export const strings = {
  drawer: {
    profile: 'Profile',
    logout: 'Logout',
    credits: 'Credits',
    settings: 'Settings',
    help: 'Help Center',
    about: 'About Us',
    contact: 'Contact Us',
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    account: 'Account',
    my_account: 'My Account',
    account_settings: 'Account Settings',
    profile_settings: 'Profile Settings',
    my_profile: 'My Profile',
    logout_confirmation: 'Are you sure you want to logout?',
    version: 'Version',
    confirm_logout: 'Confirm Logout',
    logout_confirmation_message: 'Are you sure you want to sign out?',
    dashboard: 'Dashboard',
    work_orders: 'Work Orders',
    parts: 'Parts',
    assets: 'Assets',
    copilot: 'Copilot',
    main_menu: 'Main Menu',
    account_info: 'Account Info',
    help_support: 'Help & Support',
    contact_support: 'Contact Support',
    sign_out: 'Sign Out',
    not_available: 'Not available',
  },
  login: {
    email: 'Email',
    password: 'Password',
    forgot_password: 'Forgot Password?',
    dont_have_account: 'Don’t have an account?',
    sign_up: 'Sign up',
    sign_in: 'Sign In',
    by_signing_in_you_agree_to_our: 'By signing in, you agree to our',
    terms: 'Terms',
    privacy_policy: 'Privacy Policy',
    and: 'and',
    enter_email: 'Enter email',
    phone_number: 'Enter phone number',
    phone_number_label: 'Phone Number',
    updating: 'Updating...',
    update: 'Update',
    phone_numberText: 'Phone Number',
    alternative_access: 'alternative access',
    continue_email: 'Continue with Email',
    continue_phone: 'Continue with Phone',
    enterprise: 'Enterprise?',
  },
  signup: {
    title: 'Create an Account',
    subtitle: 'Sign up to get started',
    first_name: 'First Name',
    last_name: 'Last Name',
    email: 'Email',
    phone_number: 'Phone Number',
    password: 'Password',
    confirm_password: 'Confirm Password',
    sign_up: 'Sign Up',
    already_have_account: 'Already have an account?',
    sign_in: 'Sign In',
    enter_first_name: 'Enter first name',
    enter_last_name: 'Enter last name',
    enter_email: 'Enter email',
    enter_phone: 'Enter phone number',
    enter_password: 'Enter password',
    enter_confirm_password: 'Confirm your password',
  },
  profile: {
    edit_profile: 'Edit Profile',
    first_name: 'First Name',
    last_name: 'Last Name',
    enter_first_name: 'Enter first name',
    enter_last_name: 'Enter last name',
    account_role: 'Account Role',
    enter_account_role: 'Enter account role',
    email: 'Email',
    enter_email: 'Enter email',
    phone_number: 'Enter phone number',
    phone_numberText: 'Phone Number',
    access_code: 'Access Code',
    hourly_rate: 'User Hourly Rate',
    remove_picture_title: 'Remove Profile Picture',
    remove_picture_message:
      'Are you sure you want to remove your profile picture?',
    remove: 'Remove',
    updating: 'Updating...',
    update: 'Update',
  },
  reset_password: {
    reset_password: 'Reset Password',
    enter_your_account_email_address: 'Enter your account email address',
    send_otp: 'Send OTP',
    get_otp: 'Get OTP',
    return_to_sign_in: 'Return to Sign in',
    enter_your_account_email_address_we_will_send_an_otp_to_reset_your_password:
      'Enter your account email address, we will send an OTP to reset your password.',
    enter_the_otp_sent_to_your_email: 'Enter the OTP sent to your email',
    enter_the_new_password: 'Enter the new password',
    confirm_new_password: 'Confirm new password',
    reset_password_successfully: 'Password reset successfully',
    email: 'Email',
    enter_email: 'Enter email',
  },
  error: {
    something_went_wrong: 'Something went wrong',
  },
  update_password: {
    reset_password: 'Reset Password',
    email: 'Email',
    enter_your_email: 'Enter your email',
    new_password: 'New password',
    confirm_password: 'Confirm password',
    submit: 'Submit',
    password: 'Password',
  },
  verify_otp: {
    if_you_received_a_code_you_can_enter_it:
      'If you received a code you can enter it',
    resend_otp: 'Resend OTP?',
    resend_in: 'Resend OTP in',
    we_sent_the_code_to: 'We sent the code to',
    verify: 'Verify',
    verify_email: 'We just send a OTP to your verified Email.',
    resend_time: 'Your OTP will expire in',
  },
  feedback: {
    enter_your_feedback: 'Enter your feedback here...',
    provide_feedback: 'Provide Feedback',
    submit: 'Submit',
  },
  network_error: {
    retry: 'Retry',
  },
  app: {
    iosStoreURL: '',
    androidStoreURL:
      '',
    newVersion_available:
      ' A new version of the app is available. Would you like to update it?',
    release_notes: 'Release Notes',
    new_release_notes: `Message Controls - Message editing and full copy support added.
  Performance Enhancements - Improved app stability and responsiveness.
  `,
    new_update_available: 'New Update Available',
    do_it_later: "I'll Do It Later",
    keep_update:
      'Keep your app up to date for the best experience and latest improvements.',
  },
  common: {
    yes: 'Yes',
    no: 'No',
    na: 'N/A',
    cancel: 'Cancel',
    try_again: 'Try Again',
    go_back: 'Go Back',
    apply: 'Apply',
  },
  emptyState: {
    no_data_available: 'No Data Available',
    no_data_found_for: "We didn't find any data for",
    retry: 'Retry',
    server_error: 'Server Error',
    server_error_desc: 'Oops! Something Went Wrong. Please try again later.',
    fetch_error: 'Unable to fetch data. Please try again.',
    network_error: 'Network Error',
    network_error_desc: 'Please check your internet connection and try again.',
    load_failed: 'Failed to load data.',
  },
  filter: {
    title: 'Filter',
    placeholder: 'Select filter',
    clear: 'Clear Filter',
  },
  contact_support: {
    title: 'Contact Support',
    how_can_we_help: 'How can we help?',
    request_type: 'Request Type',
    select_request_type: 'Select request type',
    subject: 'Subject',
    subject_placeholder: 'Enter subject',
    details: 'Request Details',
    details_placeholder: 'Enter request details...',
    sending: 'Sending...',
    send_request: 'Send Request',
    sending_success_fallback: 'Success',
    sending_failed_fallback: 'Failed to send message. Please try again.',
    select_request_type_modal_title: 'Select Request Type',
    feedback_types: {
      support: 'Support',
      feedback: 'Feedback',
      upgrade: 'Upgrade',
      issues: 'Issues',
      integration: 'Integration',
    },
  },
  commonHeaders: {
    forgot_password: 'Forgot Password',
    create_password: 'Create Password',
    contact_support: 'Contact Support',
    password_changed: 'Password Changed!',
  },
  no_internet: {
    whoops: 'Whoops!',
    message:
      'No internet connection was found. Check your connection or try again.',
  },
  profile_picture: {
    title: 'Profile Picture',
    no_image_selected: 'No Image Selected',
  },
  update_success: {
    title: 'Password Changed!',
    subtitle: 'Your password has been changed\n successfully.',
    back_to_sign_in: 'Back to sign in',
  },
};
